import type { ProviderDefinition } from "./types";

/**
 * Every provider the architecture is designed for.
 *
 * `status: "planned"` means the adapter is not written yet. They are listed
 * because the data model, sync bookkeeping and normalisation layer already
 * accommodate them: adding one is a single adapter file plus flipping this
 * flag, with no schema migration and no UI change.
 */
export const PROVIDERS: ProviderDefinition[] = [
  {
    id: "google_calendar",
    name: "Google Calendar",
    domain: "calendar",
    description: "Events, attendees and calendars",
    authKind: "oauth2",
    scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
    reads: ["Event titles, times and locations", "Attendee names", "Which calendar each event belongs to"],
    status: "available",
    incremental: true,
  },
  {
    id: "outlook_calendar",
    name: "Outlook Calendar",
    domain: "calendar",
    description: "Events from Microsoft 365",
    authKind: "oauth2",
    scopes: ["Calendars.Read"],
    reads: ["Event titles, times and locations", "Attendee names"],
    status: "planned",
    incremental: true,
  },
  {
    id: "apple_calendar",
    name: "Apple Calendar",
    domain: "calendar",
    description: "Events over CalDAV or an .ics subscription",
    authKind: "api_key",
    scopes: [],
    reads: ["Event titles, times and locations"],
    status: "planned",
    incremental: false,
  },
  {
    id: "todoist",
    name: "Todoist",
    domain: "tasks",
    description: "Tasks and projects",
    authKind: "oauth2",
    scopes: ["data:read"],
    reads: ["Task titles, due dates and completion", "Project names"],
    status: "planned",
    incremental: true,
  },
  {
    id: "linear",
    name: "Linear",
    domain: "tasks",
    description: "Issues assigned to you",
    authKind: "oauth2",
    scopes: ["read"],
    reads: ["Issue titles, states and due dates", "Project and cycle names"],
    status: "planned",
    incremental: true,
  },
  {
    id: "notion",
    name: "Notion",
    domain: "notes",
    description: "Pages and databases",
    authKind: "oauth2",
    scopes: ["read_content"],
    reads: ["Page titles and content from the databases you share"],
    status: "planned",
    incremental: true,
  },
  {
    id: "gmail",
    name: "Gmail",
    domain: "communication",
    description: "Follow-ups and commitments detected in mail",
    authKind: "oauth2",
    scopes: ["https://www.googleapis.com/auth/gmail.metadata"],
    reads: ["Message metadata only, never message bodies"],
    status: "planned",
    incremental: true,
  },
  {
    id: "slack",
    name: "Slack",
    domain: "communication",
    description: "Saved items and reminders",
    authKind: "oauth2",
    scopes: ["reminders:read", "stars:read"],
    reads: ["Your saved items and reminders"],
    status: "planned",
    incremental: false,
  },
  {
    id: "apple_health",
    name: "Apple Health",
    domain: "health",
    description: "Sleep, heart rate, HRV, steps and weight",
    authKind: "file_import",
    scopes: [],
    reads: ["Daily health metrics you choose to export"],
    status: "planned",
    incremental: false,
  },
  {
    id: "oura",
    name: "Oura",
    domain: "health",
    description: "Sleep stages, readiness and HRV",
    authKind: "oauth2",
    scopes: ["daily", "heartrate"],
    reads: ["Daily sleep, readiness and activity summaries"],
    status: "planned",
    incremental: true,
  },
  {
    id: "garmin",
    name: "Garmin",
    domain: "fitness",
    description: "Activities, sleep and body battery",
    authKind: "oauth2",
    scopes: ["activity:read", "sleep:read"],
    reads: ["Workout summaries", "Daily sleep and activity"],
    status: "planned",
    incremental: true,
  },
  {
    id: "fitbit",
    name: "Fitbit",
    domain: "health",
    description: "Steps, sleep and heart rate",
    authKind: "oauth2",
    scopes: ["activity", "sleep", "heartrate", "weight"],
    reads: ["Daily activity, sleep and heart rate"],
    status: "planned",
    incremental: true,
  },
  {
    id: "strava",
    name: "Strava",
    domain: "fitness",
    description: "Runs, rides and swims",
    authKind: "oauth2",
    scopes: ["activity:read"],
    reads: ["Activity type, duration, distance and heart rate"],
    status: "planned",
    incremental: true,
  },
  {
    id: "plaid",
    name: "Plaid",
    domain: "finance",
    description: "Bank balances and transactions",
    authKind: "oauth2",
    scopes: ["transactions", "accounts"],
    reads: ["Account names and balances", "Transaction dates, amounts and merchants"],
    status: "planned",
    incremental: true,
  },
  {
    id: "google_drive",
    name: "Google Drive",
    domain: "files",
    description: "Documents linked to projects",
    authKind: "oauth2",
    scopes: ["https://www.googleapis.com/auth/drive.metadata.readonly"],
    reads: ["File names and links, not file contents"],
    status: "planned",
    incremental: true,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    domain: "files",
    description: "Documents linked to projects",
    authKind: "oauth2",
    scopes: ["files.metadata.read"],
    reads: ["File names and links, not file contents"],
    status: "planned",
    incremental: true,
  },
  {
    id: "spotify",
    name: "Spotify",
    domain: "communication",
    description: "Listening time, for time analytics",
    authKind: "oauth2",
    scopes: ["user-read-recently-played"],
    reads: ["Recently played track timestamps"],
    status: "planned",
    incremental: true,
  },
];

export const DOMAIN_LABEL: Record<ProviderDefinition["domain"], string> = {
  calendar: "Calendar",
  tasks: "Tasks",
  notes: "Notes and documents",
  health: "Health",
  fitness: "Fitness",
  finance: "Finance",
  files: "Files",
  communication: "Communication",
};

export const AUTH_LABEL: Record<ProviderDefinition["authKind"], string> = {
  oauth2: "OAuth",
  api_key: "API key",
  file_import: "File import",
  device: "On-device",
};

export function providersByDomain() {
  const map = new Map<ProviderDefinition["domain"], ProviderDefinition[]>();
  for (const provider of PROVIDERS) {
    map.set(provider.domain, [...(map.get(provider.domain) ?? []), provider]);
  }
  return map;
}
